services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usvibe
    ports:
      - "5432:5432"
    volumes:
      - usvibe_pgdata:/var/lib/postgresql/data

volumes:
  usvibe_pgdata:
